### ISSUE TITLE
Double-check content of main

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-digital-cash-sc#2]
This repository was initialized from `mx-sdk-rs/contracts/examples/digital-cash` (master branch).

[All git history was kept](https://github.com/multiversx/mx-digital-cash-sc/commits/main).

`filter-repo` command invocation was:

```
git filter-repo --subdirectory-filter contracts/examples/digital-cash --to-subdirectory-filter digital-cash --tag-rename 'contracts/examples/digital-cash':'digital-cash'
```

References:
 - https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

In order to review the initialization flow, run the following check:

```
git clone -b master git@github.com:multiversx/mx-sdk-rs.git
git clone -b main git@github.com:multiversx/mx-digital-cash-sc.git
git diff --no-index ./mx-digital-cash-sc/digital-cash ./mx-sdk-rs/contracts/examples/digital-cash/
```

`git diff` should report no delta.

**Comment by andreibancioiu** [comment]
Checked :heavy_check_mark:

**Comment by alyn509** [comment]
Checked :white_check_mark:

**Comment by popenta** [comment]
Checked ✅
